# Select service mode - Defaults to STANDARD_ALL

serviceMode: STANDARD_ALL

# A unique name for the cluster that this service node/instance belongs to; use alphanumeric and underscores only.
cluster: ci_default


# What name should this server register itself under in the Badger monitoring system?
serverStartedListeners:
  - class: com.bazaarvoice.emodb.plugins.badger.BadgerServerStartedListener
    config:
      badgerServiceName: emodb.service.ci_default
  - class: com.bazaarvoice.emodb.plugins.cabertoss.CabertossServerStartedListener

# Define how yammer metrics should be pushed to third-party metrics aggregators/reporters
#  whiteList:  # Exclude measurements that we don't use in Datadog graphs or alerts
#  - ".*$(?<!5MinuteRate|15MinuteRate|meanRate|min|max|mean|stddev|95percentile|99percentile|999percentile)"

metrics:
  reporters:
    - type: datadogExpansionFiltered
      host: ci-emodb-app-093bbb0ac789f8e50.qa.us-east-1.nexus.bazaarvoice.com
      excludes:
        - ch.qos.logback
        - com.bazaarvoice.ostrich.pool
      excludeExpansions:
        - 5MinuteRate
        - 15MinuteRate
        - meanRate
        - stddev
      transport:

        type: http
        apiKey: <FIXME>


# Where does the system store information such as table definitions?
systemTablePlacement: app_global:sys

dataCenter:
  currentDataCenter: us-east-1-qa           # Which data center does this server belong to?
  cassandraDataCenter: us-east-qa       # What is the name of this DataCenter as configured in Cassandra's NetworkTopologyStrategy?
  systemDataCenter: us-east-1-qa             # All CREATE/DROP TABLE operations must occur in a single data center.  Which one is it?
  dataCenterServiceUri: http://emodb.ci.qa.us-east-1.nexus.bazaarvoice.com:8080     # Load-balanced highly available base URL for the EmoDB service (ie. Amazon ELB base url).
  dataCenterAdminUri: http://emodb.ci.qa.us-east-1.nexus.bazaarvoice.com:8081         # Load-balanced highly available base URL for the EmoDB administration tasks (ie. Amazon ELB base url).
  systemDataCenterServiceUri: http://emodb.ci.qa.us-east-1.nexus.bazaarvoice.com:8080        # Load-balanced highly available base URL for the EmoDB system data center

  ignoredDataCenters:
    - us-east-1
    - eu-west-1



systemOfRecord:
  deltaBlockSizeInKb: 16
  cellTombstoneCompactionEnabled: true
  cellTombstoneBlockLimit: 2

  # How long should we retain historical deltas? To disable, use PT0S

  historyTtl: PT48H


  # All valid placement strings for create table operations.
  validTablePlacements:
    - "app_global:sys"
    - "app_global:default"
    - "catalog_global:cat"
    - "ugc_global:ugc"
    - "ugc_us:ugc"
    - "ugc_eu:ugc"


  # A per-keyspace map of Cassandra connection settings
  cassandraClusters:
    ci_sor_ugc_default:
      cluster: ci_sor_ugc_default
      #Note: clusterMetric has to be unique from other clusters in any service
      clusterMetric: sor_ugc_default
      dataCenter: us-east-qa
      zooKeeperServiceName: ci_sor_ugc_default-qa-cassandra
      maxConnectionsPerHost: 60
      latencyAware: true
      partitioner: bop
      healthCheck:
        name: sor-ugc-cassandra
      keyspaces:
        app_global: {}
        ugc_global: {}

        ugc_us: {}

    ci_sor_cat_default:
      cluster: ci_sor_cat_default
      clusterMetric: sor_cat_default
      dataCenter: us-east-qa
      zooKeeperServiceName: ci_sor_cat_default-qa-cassandra
      maxConnectionsPerHost: 60
      latencyAware: true
      partitioner: bop
      healthCheck:
        name: sor-cat-cassandra
      keyspaces:
        catalog_global: {}


  auditWriter:
    logBucket: bv-emodb-audit-qa-us
    logPath: ci
    logBucketRegion: us-east-1
    stagingDir:  /opt/bazaarvoice/emodb/audit_logs

  slowQueryLog:
    tooManyDeltasThreshold: 20
    file:
      type: file
      currentLogFilename: /opt/bazaarvoice/emodb/logs/slow-query.log
      archivedLogFilenamePattern: /opt/bazaarvoice/emodb/logs/slow-query-%d.log.gz
      archivedFileCount: 21

  # Stash root for this cluster's content
stashRoot:  s3://emodb-us-east-1-qa/stash/ci

# to exclude the tables from the daily stash run (optional property)


databus:
  longPollPollingThreadCount: 0
  longPollKeepAliveThreadCount: 0
  masterFanoutPartitions: 2
  dataCenterFanoutPartitions: 3
  # Cassandra connection settings
  cassandra:
    cluster: ci_us_east_1_databus_default
    clusterMetric: databus
    dataCenter: us-east-qa
    zooKeeperServiceName: ci_us_east_1_databus_default-qa-cassandra
    maxConnectionsPerHost: 60
    latencyAware: true
    partitioner: random
    healthCheck:
      name: databus-cassandra
    keyspaces:
      databus: {}


queueService:
  # Cassandra connection settings
  cassandra:
    cluster: ci_us_east_1_databus_default
    clusterMetric: queue
    dataCenter: us-east-qa
    zooKeeperServiceName: ci_us_east_1_databus_default-qa-cassandra
    maxConnectionsPerHost: 60
    latencyAware: true
    partitioner: random
    healthCheck:
      name: queue-cassandra
    keyspaces:
      queue: {}


blobStore:
  # All valid placement strings for create table operations.
  validTablePlacements:
    - "media_global:ugc"
    - "media_us:ugc"
    - "media_eu:ugc"

    - "blob_global:media"
    - "blob_us:media"
    - "blob_eu:media"



  placementsUnderMove:
    "media_global:ugc": blob_global:media
    "media_us:ugc": blob_us:media
    "media_eu:ugc": blob_eu:media


  # A per-keyspace map of Cassandra connection settings
  cassandraClusters:
    ci_sor_ugc_default:
      cluster: ci_sor_ugc_default
      clusterMetric: sor_ugc_default_blob
      dataCenter: us-east-qa
      zooKeeperServiceName: ci_sor_ugc_default-qa-cassandra
      maxConnectionsPerHost: 60
      latencyAware: true
      partitioner: bop
      healthCheck:
        name: media-cassandra
      keyspaces:
        # media_xxx keyspaces will always reside with the UGC cluster. blob_xxx have their own cassandra cluster
        media_global: {}

        media_us: {}



    ci_sor_blob_default:
      cluster: ci_sor_blob_default
      #Note: clusterMetric has to be unique from other clusters in any service
      clusterMetric: sor_blob_default
      dataCenter: us-east-qa
      zooKeeperServiceName: ci_sor_blob_default-qa-cassandra
      maxConnectionsPerHost: 60
      latencyAware: true
      partitioner: bop
      healthCheck:
        name: blob-cassandra
      keyspaces:
        blob_global: {}

        blob_us: {}




  approvedContentTypes:
    - application/json
    - audio/aac
    - audio/mp4
    - audio/mpeg
    - audio/ogg
    - audio/wav
    - image/bmp
    - image/gif
    - image/jpeg
    - image/png
    - image/tiff
    - image/x-xbitmap
    - text/plain
    - video/mp4
    - video/mpeg
    - video/ogg
    - video/quicktime
    - video/x-msvideo

cqlDriver:
  singleRowFetchSize: 100
  singleRowPrefetchLimit: 50
  multiRowFetchSize: 100
  multiRowPrefetchLimit: 50



# Configure the ZooKeeper connection used for Ostrich service discovery.
zooKeeper:
  connectString: zookeeper1.qa.us-east-1.nexus.bazaarvoice.com:2181,zookeeper2.qa.us-east-1.nexus.bazaarvoice.com:2181,zookeeper3.qa.us-east-1.nexus.bazaarvoice.com:2181
  namespace: ci/us-east-1

# Configure the HTTP client that EmoService uses to make outbound requests.
httpClient:
  connectionTimeout: 1s         # Timeout after 1 second while connecting.
  timeout: 10s                  # Timeout after 10 seconds while reading or writing.
  timeToLive: 10m               # Keep connections open for 10 minutes.
  cookiesEnabled: false         # Don't track cookies.
  gzipEnabled: false
  gzipEnabledForRequests: false
  minThreads: 1                 # Thread pool for JerseyClient's async requests.
  maxThreads: 128
  keepAlive: 2s

auth:
  adminApiKey:       "<FIXME>"
  replicationApiKey: "<FIXME>"
  compControlApiKey: "<FIXME>"
  anonymousRoles:
    - reserved/anonymous

server:
  applicationConnectors:
    - type: instrumentedHttp
      port: 8080
  adminConnectors:
    - type: instrumentedHttp
      port: 8081

  gzip:
    # Most responses are small and not worth compressing.  Reduce CPU.
    enabled: false

    # If gzip is enabled, don't compress binary data types (ie. BlobStore input/output)
    compressedMimeTypes:
      - text/plain
      - text/html
      - text/xml
      - application/json
      - application/x.json-condition
      - application/x.json-delta
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /opt/bazaarvoice/emodb/logs/requests.log
        archivedLogFilenamePattern: /opt/bazaarvoice/emodb/logs/requests-%d{yyyy-MM-dd-HH}.log.gz
        archivedFileCount: 21

# Configure Logback logging
logging:
  loggers:
    "com.bazaarvoice": INFO
    "org.apache.zookeeper": OFF
    "com.netflix.curator": WARN
    "com.amazonaws.http.AmazonHttpClient": WARN
    "org.apache.shiro": WARN
  appenders:
    - type: file
      threshold: INFO
      currentLogFilename: /opt/bazaarvoice/emodb/logs/emodb.log
      archivedLogFilenamePattern: /opt/bazaarvoice/emodb/logs/emodb-%d.log.gz
      archivedFileCount: 30
      timeZone: UTC
    - type: cabertoss